# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CFD-Optimal Alignment
#'
#' Uses a modified Needleman-Wunsch algorithm to calculate the alignment with the maximum CFD score.
#'
#' @param rna Character representation of the guide. Should be represented as DNA, valid characters include ['A','C','G','T']. Must be 20 nucleotides long.
#' @param dna Character representation of the target target sequences to search for an alignment. Should be represented as DNA, valid characters include ['A','C','G','T']. No length requirement.
#' @return A data.frame will be returned with one row for each genome sequence provided, containing the optimal alignment and CFD score, and information about the location of the alignment.
#' @name private_optimal_alignment
private_optimal_alignment <- function(activity_scores, query, genome, allow_bulge) {
    .Call(`_CFDscoRe_private_optimal_alignment`, activity_scores, query, genome, allow_bulge)
}

