# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimal_alignment <- function(vpenalty_dir, query, genome) {
    .Call(`_CFDscoRe_optimal_alignment`, vpenalty_dir, query, genome)
}

